[package]
name = "f1-api"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["full"] }
